services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/postgres?sslmode=disable
    ports:
      - '8000:8000'
    depends_on:
      - db

  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    ports:
      - '3000:3000'
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    depends_on:
      - goapp
    environment:
      - NEXT_PUBLIC_API_URL=http://13.214.139.63/:8000

volumes:
  pgdata: {}
